apiVersion: v1
kind: Deployment
metadata:
  name: nginx-depoyment
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.0
          ports:
          - containerPort: 8080